baseurl = "/"
languageCode = "en-us"
title = "Kiwi Dreaming"

[params]
  description = "Coming soon."
  email = "hello@kiwidreaming.nz"

 [[menu.main]]
    name = "About2"
    url  = "/about"
    weight = 1
